services:
  traefik:
    image: traefik:v3.7
    container_name: traefik
    restart: unless-stopped
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./config/traefik.yml:/etc/traefik/traefik.yml:ro
      - ./data/certs:/var/traefik/certs/:rw
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.traefik.rule=Host(`traefik.lan.sumitkpandit.in`)
      - traefik.http.routers.traefik.entrypoints=websecure
      - traefik.http.routers.traefik.tls=true
      - traefik.http.routers.traefik.tls.certresolver=cloudflare
      - traefik.http.routers.traefik.service=api@internal
      - homepage.group=Infrastructure
      - homepage.icon=traefik.svg
      - homepage.name=Traefik
      - homepage.href=https://traefik.lan.sumitkpandit.in
      - homepage.description="Reverse proxy and load balancer for managing your services"

networks:
  traefik-network:
    external: true