services:
  radarr:
    image: lscr.io/linuxserver/radarr:6.3.0
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Kolkata
    volumes:
      - ./config:/config
      - /mnt/data/Storage/Movies:/movies #optional
      - /mnt/data/Storage/Downloads/qBittorrent:/downloads #optional
    restart: unless-stopped
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.radarr.rule=Host(`radarr.lan.sumitkpandit.in`)
      - traefik.http.routers.radarr.entrypoints=websecure
      - traefik.http.routers.radarr.tls=true
      - traefik.http.routers.radarr.tls.certresolver=cloudflare
      - traefik.http.services.radarr.loadbalancer.server.port=7878
      - homepage.group=Application
      - homepage.name=Radarr
      - homepage.icon=radarr.svg
      - homepage.href=https://radarr.lan.sumitkpandit.in
      - homepage.description=Movie collection manager
      - homepage.widget.type=radarr
      - homepage.widget.url=https://radarr.lan.sumitkpandit.in
      - homepage.widget.key=${KEY}
      - homepage.widget.enableQueue=true

networks:
  traefik-network:
    external: true
