services:
  homepage:
    image: ghcr.io/gethomepage/homepage:v1.13.2
    container_name: homepage
    restart: unless-stopped
    environment:
      - HOMEPAGE_ALLOWED_HOSTS=home.sumitkpandit.in,homepage.lan.sumitkpandit.in,lan.sumitkpandit.in
    volumes:
      - ./config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/data:/mnt/data:ro
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.homepage.rule=Host(`lan.sumitkpandit.in`)
      - traefik.http.routers.homepage.entrypoints=websecure
      - traefik.http.routers.homepage.tls.certresolver=cloudflare
      - traefik.http.services.homepage.loadbalancer.server.port=3000
      - homepage.group=Application
      - homepage.icon=homepage.png
      - homepage.name=Homepage
      - homepage.href=https://lan.sumitkpandit.in
      - homepage.description=Personal dashboard for managing your services

networks:
  traefik-network:
    external: true