services:
  adguard-home:
    image: adguard/adguardhome:v0.107.77
    container_name: adguard-home
    restart: unless-stopped
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8001:80/tcp"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.adgaurd-home.rule=Host("adguard.home.sumitkpandit.in")
      - traefik.http.routers.adgaurd-home.entrypoints=web
      - traefik.http.routers.adgaurd-home.tls=true
      - traefik.http.routers.adgaurd-home.tls.certresolver=cloudflare

networks:
  traefik-network:
    external: true
