services:
  adguard-home:
    image: adguard/adguardhome:v0.107.77
    container_name: adguard-home
    restart: unless-stopped
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "3001:3000/tcp"
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.adguard-home.rule=Host(`adguard.lan.sumitkpandit.in`)
      - traefik.http.routers.adguard-home.entrypoints=websecure
      - traefik.http.routers.adguard-home.tls=true
      - traefik.http.routers.adguard-home.tls.certresolver=cloudflare
      - traefik.http.services.adguard-home.loadbalancer.server.port=80
      - homepage.group=Infrastructure
      - homepage.icon=adguard-home.svg
      - homepage.name=AdGuard Home
      - homepage.href=https://adguard.lan.sumitkpandit.in
      - homepage.description=Network-wide ads & trackers blocking DNS server
      - homepage.widget.type=adguard
      - homepage.widget.url=https://adguard.lan.sumitkpandit.in
      - homepage.widget.username=${ADGUARD_USERNAME}
      - homepage.widget.password=${ADGUARD_PASSWORD}

networks:
  traefik-network:
    external: true
