services:
  hermes:
    image: nousresearch/hermes-agent:v2026.7.7.2
    container_name: hermes
    restart: unless-stopped
    volumes:
      - ./data:/opt/data
    environment:
      - HERMES_DASHBOARD=1
    command: gateway run
    networks:
      - traefik-network
    labels:
      - homepage.group=Applications
      - homepage.name=Hermes Agent
      - homepage.icon=hermes-icon.svg
      - homepage.href=https://hermes.lan.sumitkpandit.in
      - homepage.description=The Agent That Grows With You
      - traefik.enable=true
      - traefik.http.routers.hermes-gateway.rule=Host(`hermes-gateway.lan.sumitkpandit.in`)
      - traefik.http.routers.hermes-gateway.entrypoints=websecure
      - traefik.http.routers.hermes-gateway.tls.certresolver=cloudflare
      - traefik.http.routers.hermes-gateway.service=hermes-gateway
      - traefik.http.services.hermes-gateway.loadbalancer.server.port=8642
      - traefik.http.routers.hermes.rule=Host(`hermes.lan.sumitkpandit.in`)
      - traefik.http.routers.hermes.entrypoints=websecure
      - traefik.http.routers.hermes.tls.certresolver=cloudflare
      - traefik.http.routers.hermes.service=hermes
      - traefik.http.services.hermes.loadbalancer.server.port=9119

networks:
  traefik-network:
    external: true