#ENC[AES256_GCM,data:Xj362pFcOzzTMRPusKbRLYrCzuoLDGDvZ8N0ZAWgV0DYJW5nfzRIBa36zvs0jkaZCg/tz7cLehDdqGdhRVTyekiV8QadGmAqcs9dHlFh,iv:Efob1B5Vazl3mO9LEVR/7tmX67EmNZWO7xQpK1XeQpo=,tag:XbWFEWc1DsIk9sI+U7oH1w==,type:comment]
#ENC[AES256_GCM,data:NhFFG9h3L3u7jRu7dWx0c2vGCsOhuNdYQoMR8YHlzCTLa7/l9kWXEX1GCc0oaC+gGXhZ5pjsIoVKQZXo7NNX+g==,iv:zkDSwo9t4BLf8wxMegox30gnAOAWB/ZOOQYrTKYf9UQ=,tag:mGSqU+XW7khlN+C09MGQXA==,type:comment]
#ENC[AES256_GCM,data:Z6Tl73W6T6vNo7fzPoleEGk/gFK4IkbQ8+d/oQSvZknOZ/HY4Kg02vQr59C6fQGb5Wm0BZ64UslRA6XOXDWzfjxWsu0A,iv:kqAqazjaGAX/B+2LfkywL+Nfpv96DB2VaKJj3CwBkU0=,tag:1bE/qPrZXjzITYe4x5gJ4g==,type:comment]
#ENC[AES256_GCM,data:Uiernvmx5hsQUNAvRfeKq6nhErOFaediM374b5X1/DDGZ6oIMDNCJytZ/Y5J5tuzp95Aa4ozsgQ=,iv:b3NfatH6kkrfpjAWygX9y6DyeCYiDCu7x0dAGORCrFE=,tag:1Knwak1X6YGxfbnUsiVw3Q==,type:comment]
tailscale_auth_key: ""
#ENC[AES256_GCM,data:UljQKAjuF6R7n57Q7px09PDZoDtwDirKqUojqRxaOMKNpgOy8aE3FlLBHuIpcK0P9pPPcrzdSfiZ1geJgDwGliFmDhjzeKhrz3YfaSCBh5p7ANI=,iv:fh0AasA3i1K/8/J6ICY/qunzaAUt/I1Aii5sF6VmFuI=,tag:TYddW4La9bePM5Sh6jJ/GQ==,type:comment]
#ENC[AES256_GCM,data:47kHodB9fDBAEJHMFuddbsx8wFogKGJZiSX0pZGNakK6qaa2L8Q+AqDSRYUfqQCOAQDd7E89WR1NvzufstdSiLUXk92KaJQy4nK0SpQ=,iv:yaJ3qtrvBVnn3CGAUOOhiEvbArwLChCcIroKCEdlvpA=,tag:FX3FD5QyIuQzntgyJHE6zA==,type:comment]
cloudflare_api_token: ""
cloudflare_tunnel_token: ""
#ENC[AES256_GCM,data:JzFDdekTNFxYZOxivBRr2XcyMbQ0dw6gWXyFiPhBFBPZZhD8VLa6pukIiEin+dNaToXw4FqPIPK9oHeWa8LffbTz6kas2xRZoA==,iv:cd44F4TucAi45yctnlvRHCc45WRiVfhByfxlRSKZxzs=,tag:yqQF867Sy03sDhPo3p2QKg==,type:comment]
telegram_bot_token_uptime_kuma: ""
telegram_chat_id: ""
#ENC[AES256_GCM,data:RrARy+cpkcj0w0PNQGho3xx1xtyhXusRaU96YBGqv6hymPseMbP3DPtWi4XJjgxAmMvfaG+gK3bxk0xzylPUoyt4vKMuEUhFPDo=,iv:RU+jCAuRKoZsyu9/qZtgTW6zHBifmwBmz3ll1VStWDk=,tag:TXQdQPSmsqK4G8F3l7ugPQ==,type:comment]
uptime_kuma_disk_push_token: ""
uptime_kuma_backup_push_token: ""
#ENC[AES256_GCM,data:d9/dVuGyB/XsRD11MZAMbcU2OwPSoOhFgqqvaGkl3tUr8/YjYyMJ/PdImlryN2V+boWRek9jYrCzUQXfuImWbEkrWJQ7IWEEwlpZ,iv:q9cd2GfYHJcfjr+Rz4gmnqROTTmEsy24PHNyG8GQmPw=,tag:cLTOFbX8vs5n59b2ihMXJg==,type:comment]
hermes_openrouter_api_key: ""
hermes_telegram_bot_token: ""
hermes_dashboard_password: ""
#ENC[AES256_GCM,data:zk9ab7p2qENpgVz68PJVL48etFb8MAutxESBnPmfPL7S1Cz6pv7kNXXrxmMUHAhVFdRIRPdrBv5YPMoHTHRm2HF/RPXcRNKzgQ==,iv:OoG0rThrNzXf/e7gzXnJe3jrdJsNXBqQj9aRsCpo2WI=,tag:tioNSY5AzDuA7BXUEYEIAQ==,type:comment]
vpn_provider: ""
vpn_username: ""
vpn_password: ""
#ENC[AES256_GCM,data:Ea+RjbiV88sT87Wa2KYBaqfFhdlHQb7qPAjQzImk0Fx29xU5CqMcaLCAURt1ajQILphqbZhACZBZNKy3LKIu+ak/PBWYfPRAlYQ=,iv:n0qSZP7/9M52Jb8SzfQa6FgsJhAsXyiftB+Z8MXYwa0=,tag:qNcAe4x7tUxrn76NQjij6w==,type:comment]
#ENC[AES256_GCM,data:NvlyT0utF8era566urJcKvMwoLyc3HItKTHaTmhP8btMtmdidKat1G8urWgpPaXdkQpFFHYo+ouOxLB/UqTt0m9JrZDHyw==,iv:bmWaOoADYXh23hxjgWglb6FeiANWgLk4GrHbwklcHS8=,tag:sEVj5PAysVBnWaV4bPPinw==,type:comment]
restic_repository_password: ""
rclone_drive_token: ""
#ENC[AES256_GCM,data:McIbllwalKk8UIEvNsBQnnN2jlA6ynOXF1tqFQYhMzUVQoO34srCcH4RXg8QQZwvo3PcVBbyaAAO0kHfAbXSg+1fOyM=,iv:M9VsL2dwFILKrsc1RFeZB9fg2zkPKGz4qNnAZFnZnZc=,tag:A87yfWGZKfjej5qUGDxBpA==,type:comment]
internal_sonarr_api_key: ENC[AES256_GCM,data:jjiPuDVCR3sMWCgd33dJYFVR0eULQDxAjqTZQuAxEhE=,iv:8X4qK2TCs0mHR0eMM8Fo6hhCajyJMoIAhXIosj2t4OY=,tag:Z2VMA46KpmT6ZBupSjYTYw==,type:str]
internal_radarr_api_key: ENC[AES256_GCM,data:QX1Mmttpva3oPxA5HMV8WaIrZCE5fotMooq7y9I48QU=,iv:S7ShG8I/yeG+smW41O6fsctg7pYM/LmhoDadU4Mg+uM=,tag:GrsomAdWvVv0DVlkl19tzA==,type:str]
internal_prowlarr_api_key: ENC[AES256_GCM,data:t+u3G3EvScLcM0HM2TfTykclWFqPeV5NCXEZmCSzVI4=,iv:2NK6UHGbZrlVroHaLkYRs+5B5vz0B0Uu+nta0QGSo2s=,tag:HZN1nWGmHr2CJsoknqQFbQ==,type:str]
internal_bazarr_api_key: ENC[AES256_GCM,data:UqFR8nuRDDq7t/bEVpsZ0geBKlST8Gyo8wp9/gnXTuftSZWI+vgiurfLNKZaAaA2,iv:YUjTzH98KLqTNHm2vvvhj9N2xCVHgHCP5RJfOl9g6YE=,tag:Zu42bSAMQa8rcyTsX9fNlw==,type:str]
internal_jellyseerr_api_key: ENC[AES256_GCM,data:7hO25iNaleyC6eJ47CupiiBHGNoDpZrJdI3+xhni7PQ+0h1IHgTMFMEyvmhtTM4t,iv:L+s0Hvak8lsipiZeZ/fTpNeU3qIyMWv5G7NBY67hh10=,tag:46YkIBe0V8aPeuFbsBnhTg==,type:str]
internal_qbittorrent_admin_password: ENC[AES256_GCM,data:DYFMCyoEDGq60cOwdVR/lGoa4G5HEnk9,iv:7F79b7x5x6UiRC61FxsOZnMZz8OcqFvgTVTwS0xepUA=,tag:nm31tbblueLVRE9dzgmKTg==,type:str]
jellyfin_admin_username: ENC[AES256_GCM,data:jIb5Pcg=,iv:TjBTBUw8CyElPZ7FI+bjlffrWw+LrkVcuqpPx8CMYW0=,tag:fGfPMSsfqO7KPeu00NltYg==,type:str]
jellyfin_admin_password: ""
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVEJ1YTFsMGNqZ1dza2NL
            WEQ0NERDTi8vSmQ4R0pHK1NqWGE3Yy9TNXlRCnY5SDdFeEs3MUVUYkJlc2ozK01X
            WEZTdjE5WDh1aXFWa28vYSsySWtha28KLS0tIFROZExWM0cxRmVZbHNnaElMUkw3
            VkFZY1dpNjhxeE1FSmJOM094d3RoY0UKG+/xr9Nu3KvMVWgcMkjndA3tRF8azfcn
            oXk0zkhKggIQ1pCP5yGuC7vYYJxvO4ZPZRG4DakZ3/lUqAoizo/Brw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age106nehhdhzp2030eam3dt09ypaz3teq59s4pqqf776354qcwc3uuq5n30uz
    lastmodified: "2026-10-03T18:50:56Z"
    mac: ENC[AES256_GCM,data:kQuLEbghlhNny09TdlRn4NS770qsU1AW4T8fVuzlLRPZ4RfNCjLFM0n/2dRKJAQdGC2bAoNu6aZT6jz4XUKJwdc1h9eflYZMGAPg3LkEsKisd8vezdcntnD4+tMzf3AMnl6Kb7WxYP+dySf0Fsyg5rSW79Mq2AJrr81vx6p4R8c=,iv:ab2kOfYZInT6iD4SLRL3a0ovLfVjESSdTYqtvmaPmZo=,tag:hd2DetMCbFIX9CSOVASeow==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
