#ENC[AES256_GCM,data:Xj362pFcOzzTMRPusKbRLYrCzuoLDGDvZ8N0ZAWgV0DYJW5nfzRIBa36zvs0jkaZCg/tz7cLehDdqGdhRVTyekiV8QadGmAqcs9dHlFh,iv:Efob1B5Vazl3mO9LEVR/7tmX67EmNZWO7xQpK1XeQpo=,tag:XbWFEWc1DsIk9sI+U7oH1w==,type:comment]
#ENC[AES256_GCM,data:NhFFG9h3L3u7jRu7dWx0c2vGCsOhuNdYQoMR8YHlzCTLa7/l9kWXEX1GCc0oaC+gGXhZ5pjsIoVKQZXo7NNX+g==,iv:zkDSwo9t4BLf8wxMegox30gnAOAWB/ZOOQYrTKYf9UQ=,tag:mGSqU+XW7khlN+C09MGQXA==,type:comment]
#ENC[AES256_GCM,data:Z6Tl73W6T6vNo7fzPoleEGk/gFK4IkbQ8+d/oQSvZknOZ/HY4Kg02vQr59C6fQGb5Wm0BZ64UslRA6XOXDWzfjxWsu0A,iv:kqAqazjaGAX/B+2LfkywL+Nfpv96DB2VaKJj3CwBkU0=,tag:1bE/qPrZXjzITYe4x5gJ4g==,type:comment]
#ENC[AES256_GCM,data:Uiernvmx5hsQUNAvRfeKq6nhErOFaediM374b5X1/DDGZ6oIMDNCJytZ/Y5J5tuzp95Aa4ozsgQ=,iv:b3NfatH6kkrfpjAWygX9y6DyeCYiDCu7x0dAGORCrFE=,tag:1Knwak1X6YGxfbnUsiVw3Q==,type:comment]
tailscale_auth_key: ""
#ENC[AES256_GCM,data:UljQKAjuF6R7n57Q7px09PDZoDtwDirKqUojqRxaOMKNpgOy8aE3FlLBHuIpcK0P9pPPcrzdSfiZ1geJgDwGliFmDhjzeKhrz3YfaSCBh5p7ANI=,iv:fh0AasA3i1K/8/J6ICY/qunzaAUt/I1Aii5sF6VmFuI=,tag:TYddW4La9bePM5Sh6jJ/GQ==,type:comment]
#ENC[AES256_GCM,data:47kHodB9fDBAEJHMFuddbsx8wFogKGJZiSX0pZGNakK6qaa2L8Q+AqDSRYUfqQCOAQDd7E89WR1NvzufstdSiLUXk92KaJQy4nK0SpQ=,iv:yaJ3qtrvBVnn3CGAUOOhiEvbArwLChCcIroKCEdlvpA=,tag:FX3FD5QyIuQzntgyJHE6zA==,type:comment]
cloudflare_api_token: ""
cloudflare_tunnel_token: ""
#ENC[AES256_GCM,data:JzFDdekTNFxYZOxivBRr2XcyMbQ0dw6gWXyFiPhBFBPZZhD8VLa6pukIiEin+dNaToXw4FqPIPK9oHeWa8LffbTz6kas2xRZoA==,iv:cd44F4TucAi45yctnlvRHCc45WRiVfhByfxlRSKZxzs=,tag:yqQF867Sy03sDhPo3p2QKg==,type:comment]
telegram_bot_token_uptime_kuma: ""
telegram_chat_id: ""
#ENC[AES256_GCM,data:RrARy+cpkcj0w0PNQGho3xx1xtyhXusRaU96YBGqv6hymPseMbP3DPtWi4XJjgxAmMvfaG+gK3bxk0xzylPUoyt4vKMuEUhFPDo=,iv:RU+jCAuRKoZsyu9/qZtgTW6zHBifmwBmz3ll1VStWDk=,tag:TXQdQPSmsqK4G8F3l7ugPQ==,type:comment]
uptime_kuma_disk_push_token: ""
uptime_kuma_backup_push_token: ""
#ENC[AES256_GCM,data:d9/dVuGyB/XsRD11MZAMbcU2OwPSoOhFgqqvaGkl3tUr8/YjYyMJ/PdImlryN2V+boWRek9jYrCzUQXfuImWbEkrWJQ7IWEEwlpZ,iv:q9cd2GfYHJcfjr+Rz4gmnqROTTmEsy24PHNyG8GQmPw=,tag:cLTOFbX8vs5n59b2ihMXJg==,type:comment]
hermes_openrouter_api_key: ""
hermes_telegram_bot_token: ""
hermes_dashboard_password: ""
#ENC[AES256_GCM,data:zk9ab7p2qENpgVz68PJVL48etFb8MAutxESBnPmfPL7S1Cz6pv7kNXXrxmMUHAhVFdRIRPdrBv5YPMoHTHRm2HF/RPXcRNKzgQ==,iv:OoG0rThrNzXf/e7gzXnJe3jrdJsNXBqQj9aRsCpo2WI=,tag:tioNSY5AzDuA7BXUEYEIAQ==,type:comment]
vpn_provider: ""
vpn_username: ""
vpn_password: ""
#ENC[AES256_GCM,data:Ea+RjbiV88sT87Wa2KYBaqfFhdlHQb7qPAjQzImk0Fx29xU5CqMcaLCAURt1ajQILphqbZhACZBZNKy3LKIu+ak/PBWYfPRAlYQ=,iv:n0qSZP7/9M52Jb8SzfQa6FgsJhAsXyiftB+Z8MXYwa0=,tag:qNcAe4x7tUxrn76NQjij6w==,type:comment]
#ENC[AES256_GCM,data:NvlyT0utF8era566urJcKvMwoLyc3HItKTHaTmhP8btMtmdidKat1G8urWgpPaXdkQpFFHYo+ouOxLB/UqTt0m9JrZDHyw==,iv:bmWaOoADYXh23hxjgWglb6FeiANWgLk4GrHbwklcHS8=,tag:sEVj5PAysVBnWaV4bPPinw==,type:comment]
restic_repository_password: ""
rclone_drive_token: ""
#ENC[AES256_GCM,data:McIbllwalKk8UIEvNsBQnnN2jlA6ynOXF1tqFQYhMzUVQoO34srCcH4RXg8QQZwvo3PcVBbyaAAO0kHfAbXSg+1fOyM=,iv:M9VsL2dwFILKrsc1RFeZB9fg2zkPKGz4qNnAZFnZnZc=,tag:A87yfWGZKfjej5qUGDxBpA==,type:comment]
internal_sonarr_api_key: ENC[AES256_GCM,data:lJ2gsQQqcz/d/sP9ehS9DxfZ9Iu8bKymtx3kna//S0us2nzqhe9qP7q2M3mMOOod,iv:jTyTPlAwACMj9gUQyJ3eXg+6CCEreh/7aH57M660Vj4=,tag:2ihlROSW4ngBL7UOCifGLA==,type:str]
internal_radarr_api_key: ENC[AES256_GCM,data:HXNr3L/Kw2PayD01YYHswTptytiA/6F7AkohkewLz5DxC8KX1Yx2hF4tG86A4EW2,iv:tsUgf8HQioy0HXn0biJtxi+JwWb0SfH8JKOaokAOeoY=,tag:G0cWTv/Yys/mearbDbVvgw==,type:str]
internal_prowlarr_api_key: ENC[AES256_GCM,data:ifOSlTCddL29S30KsU4fdNfxrFzIO9BJ3Cb8Vj6wLM0hZ9lTIwsIeQ90U1+1gw6R,iv:Q6SGi2kqlsOUl3qFOe9ghfcFMfNuwtjvvgOKsNnfAiA=,tag:mQVjavKVFxq3vWfHvTsbrQ==,type:str]
internal_bazarr_api_key: ENC[AES256_GCM,data:UqFR8nuRDDq7t/bEVpsZ0geBKlST8Gyo8wp9/gnXTuftSZWI+vgiurfLNKZaAaA2,iv:YUjTzH98KLqTNHm2vvvhj9N2xCVHgHCP5RJfOl9g6YE=,tag:Zu42bSAMQa8rcyTsX9fNlw==,type:str]
internal_jellyseerr_api_key: ENC[AES256_GCM,data:7hO25iNaleyC6eJ47CupiiBHGNoDpZrJdI3+xhni7PQ+0h1IHgTMFMEyvmhtTM4t,iv:L+s0Hvak8lsipiZeZ/fTpNeU3qIyMWv5G7NBY67hh10=,tag:46YkIBe0V8aPeuFbsBnhTg==,type:str]
internal_qbittorrent_admin_password: ENC[AES256_GCM,data:DYFMCyoEDGq60cOwdVR/lGoa4G5HEnk9,iv:7F79b7x5x6UiRC61FxsOZnMZz8OcqFvgTVTwS0xepUA=,tag:nm31tbblueLVRE9dzgmKTg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsVEJ1YTFsMGNqZ1dza2NL
            WEQ0NERDTi8vSmQ4R0pHK1NqWGE3Yy9TNXlRCnY5SDdFeEs3MUVUYkJlc2ozK01X
            WEZTdjE5WDh1aXFWa28vYSsySWtha28KLS0tIFROZExWM0cxRmVZbHNnaElMUkw3
            VkFZY1dpNjhxeE1FSmJOM094d3RoY0UKG+/xr9Nu3KvMVWgcMkjndA3tRF8azfcn
            oXk0zkhKggIQ1pCP5yGuC7vYYJxvO4ZPZRG4DakZ3/lUqAoizo/Brw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age106nehhdhzp2030eam3dt09ypaz3teq59s4pqqf776354qcwc3uuq5n30uz
    lastmodified: "2026-10-03T17:30:19Z"
    mac: ENC[AES256_GCM,data:cTnx2bhKdlzXqcdWeBln0TX3xvSHm/X1jn8pXnB42SaTPq46wOg7nIYFhtlBgAl/05yyW5q8T3zCq5ZSs8q5knT+g5y9v20jknxEGrxb9Exn5ZzcpEQT8DV15tEjq2XCADsMkmpJxXC3YZ3DF64cZ7ReZrt5Wf0t/lkTuuwpQZM=,iv:M4k8vovJTLLsm/9Pl6nu5pfdLghaiTrxz8B6Qi5UYxE=,tag:0eZ20j8np6flPUXjapomrg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.13.3
