services:
  beszel:
    image: henrygd/beszel:0.18.7
    container_name: beszel
    restart: unless-stopped

    environment:
      - APP_URL: https://beszel.lan.sumitkpandit.in

    volumes:
      - ./data/hub:/beszel_data

    networks:
      - traefik-network

    labels:
      - traefik.enable=true

      - traefik.http.routers.beszel.rule=Host(`beszel.lan.sumitkpandit.in`)
      - traefik.http.routers.beszel.entrypoints=websecure
      - traefik.http.routers.beszel.tls=true
      - traefik.http.routers.beszel.tls.certresolver=cloudflare
      - traefik.http.services.beszel.loadbalancer.server.port=8090

      # Homepage
      - homepage.group=Infrastructure
      - homepage.name=Beszel
      - homepage.icon=beszel.svg
      - homepage.href=https://beszel.lan.sumitkpandit.in
      - homepage.description=Server Monitoring

      # Homepage Widget
      - homepage.widget.type=beszel
      - homepage.widget.url=http://beszel:8090
      - homepage.widget.username=${BESZEL_USERNAME}
      - homepage.widget.password=${BESZEL_PASSWORD}
      - homepage.widget.version=2

  beszel-agent:
    image: henrygd/beszel-agent
    container_name: beszel-agent
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./data/agent:/var/lib/beszel-agent
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      - /:/extra-filesystems/os:ro
      - /mnt/data:/extra-filesystems/sd1:ro
    environment:
      LISTEN: 45876
      KEY: ${AGENT_KEY}
      TOKEN: ${AGENT_TOKEN}
      HUB_URL: https://beszel.lan.sumitkpandit.in

networks:
  traefik-network:
    external: true