services:
  uptime-kuma:
    image: louislam/uptime-kuma:2
    container_name: uptime-kuma
    restart: unless-stopped
    volumes:
      - ./data:/app/data
    networks:
      - traefik-network
    labels:
      - traefik.enable=true
      - traefik.http.routers.kuma.rule=Host(`uptime.lan.sumitkpandit.in`)
      - traefik.http.routers.kuma.entrypoints=websecure
      - traefik.http.routers.kuma.tls.certresolver=cloudflare
      - traefik.http.services.kuma.loadbalancer.server.port=3001
      - homepage.group=Infrastructure
      - homepage.icon=uptime-kuma.svg
      - homepage.name="Uptime Kuma"
      - homepage.href=https://uptime.lan.sumitkpandit.in
      - homepage.description="Simple and powerful uptime monitoring solution"

networks:
  traefik-network:
    external: true