- Infrastructure:

    - Traefik:
        icon: traefik.png
        href: https://traefik.lan.sumitkpandit.in
        description: "Traefik is a modern HTTP reverse proxy and load balancer that makes deploying microservices easy."
        widget:
          type: traefik
          url: https://traefik.lan.sumitkpandit.in

    - AdGuard:
        icon: adguard-home.png
        href: https://adguard.lan.sumitkpandit.in
        description: "AdGuard Home is a network-wide ad blocker and parental control solution."
        widget:
          type: adguard
          url: https://adguard.lan.sumitkpandit.in
          username: sumitkpandit
          password: adguardhome

    - Uptime Kuma:
        icon: uptime-kuma.png
        href: https://uptime.lan.sumitkpandit.in
        description: "Uptime Kuma is a monitoring tool that allows you to monitor the uptime of your services and websites."
        widget:
          type: uptimekuma
          url: https://uptime.lan.sumitkpandit.in
          slug: prithvi