- resources:
    cpu: true
    memory: true
    cputemp: true
    uptime: true
    network: true
    disk: 
      - /
      - /mnt/data

- openmeteo:
    label: Bengaluru # optional
    latitude: 12.9065833333
    longitude: 77.7015
    timezone: Asia/Kolkata # optional
    units: metric # or imperial
    cache: 5 # Time in minutes to cache API responses, to stay within limits
    format: # optional, Intl.NumberFormat options
      maximumFractionDigits: 1

- datetime:
    text_size: xl
    format:
      dateStyle: long
      timeStyle: short